CREATE TABLE IF NOT EXISTS groups (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS peripherals (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NUll,
	grp_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS instances (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	periph_id INTEGER NOT NULL REFERENCES peripherals(id) ON DELETE CASCADE ON UPDATE CASCADE,
	name TEXT NOT NULL,
	address INTEGER NOT NULL,

	UNIQUE (name,address) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS inst_chip (
	id INTEGER PRIMARY KEY AUTOINCREMENT ,
	inst_id INTEGER NOT NULL REFERENCES instances(id) ON DELETE CASCADE ON UPDATE CASCADE,
	chip_id INTEGER NOT NULL REFERENCES chips(id) ON DELETE CASCADE ON UPDATE CASCADE,

	UNIQUE (inst_id, chip_id) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS reg_placements (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	periph_id INTEGER  NOT NULL REFERENCES peripherals(id) ON DELETE CASCADE ON UPDATE CASCADE,
	register_id INTEGER NOT NULL REFERENCES registers(id) ON DELETE CASCADE ON UPDATE CASCADE,

	name TEXT,
	array_size INTEGER DEFAULT NULL,
	array_space INTEGER DEFAULT NULL,

	pos INTEGER NOT NULL,

	UNIQUE (name,periph_id,register_id,pos) ON CONFLICT FAIL
);

CREATE TABLE IF NOT EXISTS registers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	size INT DEFAULT 32,
	type TEXT,

	sub_periph_id INTEGER DEFAULT NULL REFERENCES peripherals(id) ON DELETE RESTRICT ON UPDATE CASCADE,

	UNIQUE (name,size) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS fields (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	size INT NOT NULL,
	position INT NOT NULL,

	UNIQUE(name,size,position) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS field_reg_placement (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	field_id INTEGER NOT NULL REFERENCES fields(id) ON DELETE CASCADE ON UPDATE CASCADE,
	reg_placement_id INTEGER NOT NULL REFERENCES reg_placements(id) ON DELETE CASCADE ON UPDATE CASCADE,
	chip_id INTEGER NOT NULL REFERENCES chips(id),
	UNIQUE (field_id,reg_placement_id,chip_id) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS chips (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS chip_field (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	chip_id INTEGER NOT NULL REFERENCES chips(id) ON DELETE CASCADE ON UPDATE CASCADE,
	field_id INTEGER NOT NULL REFERENCES fields(id) ON DELETE CASCADE ON UPDATE CASCADE,

	UNIQUE (chip_id,field_id) ON CONFLICT IGNORE
);
